// <auto-generated />
namespace MeuEcommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ClienteComprasItens : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClienteComprasItens));
        
        string IMigrationMetadata.Id
        {
            get { return "201812192147088_Cliente-Compras-Itens"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
